apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-admin-web
spec:
  type: {{ .Values.adminWeb.service.type }}
  selector:
    app: {{ .Release.Name }}-admin-web
  ports:
    - name: http
      port: {{ .Values.adminWeb.service.port }}
      targetPort: {{ .Values.adminWeb.service.port }}
