replicaCount: 1

image:
  repository: agent-portal-api
  tag: latest
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: ""
  annotations: {}

rbac:
  create: true

service:
  type: ClusterIP
  port: 4000

env:
  AUTH_BYPASS: "false"
  INITIAL_ADMIN_EMAIL: "admin@samsung.com"
  INITIAL_ADMIN_PASSWORD: "chrlghk123#"
  JWT_SECRET: "change-me"
  TYPEORM_SYNC: "true"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "agent_portal"
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
  DB_SSL: "false"
  OIDC_AUTHORIZATION_URL: ""
  OIDC_TOKEN_URL: ""
  OIDC_USERINFO_URL: ""
  OIDC_CLIENT_ID: ""
  OIDC_CLIENT_SECRET: ""
  OIDC_REDIRECT_URI: ""
  GITLAB_BASE_URL: ""
  GITLAB_TOKEN: ""
  LITELLM_BASE_URL: ""
  LITELLM_MASTER_KEY: ""
  OPENSEARCH_URL: ""
  OPENSEARCH_ADMIN_USERNAME: ""
  OPENSEARCH_ADMIN_PASSWORD: ""
  OPENSEARCH_INDEX_PREFIX: "project"
  K8S_NOTEBOOK_ENABLED: "false"
  K8S_NOTEBOOK_NAMESPACE: "agent-notebooks"
  K8S_NOTEBOOK_INGRESS_CLASS: "nginx"
  K8S_WORKSPACE_ENABLED: "false"
  K8S_WORKSPACE_NAMESPACE: "agent-workspaces"
  K8S_WORKSPACE_INGRESS_CLASS: "nginx"
  KUBECONFIG_PATH: ""
  NOTEBOOK_PVC: "shared-notebooks-pvc"
  NOTEBOOK_IMAGE: "jupyter/base-notebook:latest"
  NOTEBOOK_REQUEST_CPU: "1"
  NOTEBOOK_REQUEST_MEM_GI: "2"
  WORKSPACE_HOST_SUFFIX: "127.0.0.1.nip.io"
  WORKSPACE_IMAGE_NODE22: "agent-portal-vscode-node22:latest"
  WORKSPACE_IMAGE_NODE23: "agent-portal-vscode-node23:latest"
  WORKSPACE_IMAGE_NODE24: "agent-portal-vscode-node24:latest"
  WORKSPACE_IMAGE_PYTHON38: "agent-portal-vscode-python38:latest"
