{{- $agentNs := .Values.env.K8S_SERVING_NAMESPACE | default "agent-serving" -}}
{{- if and .Values.agentBuildServiceAccount.create (eq (.Values.env.K8S_SERVING_ENABLED | default "true") "true") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.agentBuildServiceAccount.name | default "agent-builder" }}
  namespace: {{ $agentNs }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
  {{- with .Values.agentBuildServiceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
