apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api.fullname" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "api.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "api.serviceAccountName" . }}
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            {{- range $name, $value := .Values.env }}
            - name: {{ $name }}
              value: {{ $value | quote }}
            {{- end }}
            - name: WORKSPACE_HOST_TEMPLATE
              value: {{ .Values.workspaceIngress.hostTemplate | quote }}
            - name: WORKSPACE_URL_SCHEME
              value: {{ .Values.workspaceIngress.scheme | quote }}
            - name: K8S_WORKSPACE_INGRESS_ANNOTATIONS_JSON
              value: {{ .Values.workspaceIngress.annotations | toJson | quote }}
