apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-api.fullname" . }}
  labels:
    {{- include "k8s-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "k8s-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "k8s-api.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: k8s-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            {{- range $name, $value := .Values.env }}
            - name: {{ $name }}
              value: {{ $value | quote }}
            {{- end }}
